version: '3.9'

services:
  db:
    image: mysql:8.2.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 01234567
      MYSQL_USER: docker
      MYSQL_PASSWORD: 01234567
      MYSQL_DATABASE: isi_vendor_database
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - isivendor-network

  isivendor-app:
    image: rafaelcolin/isi-vendor
    restart: always
    build: ./
    working_dir: /
    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3308/isi_vendor_database?useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 01234567
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - isivendor-network

networks:
  isivendor-network:
    driver: bridge
