security:
  jwt:
    token:
      secret-key: 53cr37
      expire-lenght: 36000000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/isi_vendor_database
    username: root
    password: 01234567
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true

  profiles:
    active: test

  mail:
    host: smtp.gmail.com
    port: 587
    username: isivendorenterprise@gmail.com
    password: kbaz bdth wjsl qtro
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
