server:
  port: 80
cors:
  originPatterns: http://localhost:3000,http://localhost:8080
file:
  upload-dir: /Code/UploadDir
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/isi_vendor_database?useTimezone=true&serverTimezone=UTC
    username: root
    password: 01234567
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  profiles:
    active: test
  mail:
    host: smtp.gmail.com
    port: 587
    username: isivendorenterprise@gmail.com
    password: kbaz bdth wjsl qtro
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
