
name: Continuous Integration with Github actions

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Build application JAR
      run: mvn clean package 

    - name: Docker compose build
      run: docker compose build

    - name: Push to DockerHub 
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/isi-vendor:latest ${{ secrets.DOCKER_USERNAME }}/isi-vendor:${{ github.run_id }}

        docker push  ${{ secrets.DOCKER_USERNAME }}/isi-vendor:${{ github.run_id }}
        docker push  ${{ secrets.DOCKER_USERNAME }}/isi-vendor:latest


    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
